headers:
  apiKey: "Bearer <Replace with Api key>"
  organisation: "<Replace with org name>"
  sourceName: "<Replace with org source>"
  url: "<replace with>" #The node name of a single document URL inside the json document array (default : "url")

basicInformation:
  array: "<replace with node name>" #the main node of the json file (default : "documents")
  filePath: "<replace with json filename>" #the main json file containing all the documents nodes (default : "docs.json")
  folder: "<path of the folder to crawl>" #folder to crawl to populate the main json document
  filetype: "<replace by file type>" #type of file to parse (default : "txt" or leave empty if you don't want to crawl a folder)
